version: '3.8'

services:
  # nextjs-prod:
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   restart: always

  nextjs-dev-jtekt:
    build:
      context: .
      dockerfile: dockerfile.dev.jtekt
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_MODE=jtekt
      - NEXT_TEST=TEST1
      - NEXT_PUBLIC_URL_API=http://localhost:3010/api/v1
      - NEXT_PUBLIC_SOCKET_SERVER_URL=http://localhost:3010
    command: sh -c "yarn dev"
  nextjs-dev-supplier:
    build:
      context: .
      dockerfile: dockerfile.dev.supplier
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    environment:
      - NEXT_MODE=supplier
      - NEXT_TEST=TEST2
      - NEXT_PUBLIC_URL_API=http://localhost:3010/api/v1
      - NEXT_PUBLIC_SOCKET_SERVER_URL=http://localhost:3010
    command: sh -c "yarn dev"
