version: '3.8'

services:
  nextjs-dev-jtekt:
    build:
      context: .
      dockerfile: dockerfile.dev.jtekt
    volumes:
      - ./src:/app/src
    ports:
      - "3300:3000"
    environment:
      - NEXT_MODE=jtekt
      - NEXT_TEST=TEST1
      - NEXT_PUBLIC_URL_API=http://localhost:3600/api/v1
      - NEXT_PUBLIC_SOCKET_SERVER_URL=http://localhost:3600
    command: sh -c "yarn dev"
  nextjs-dev-supplier:
    build:
      context: .
      dockerfile: dockerfile.dev.supplier
    volumes:
      - ./src:/app/src
    ports:
      - "3301:3000"
    environment:
      - NEXT_MODE=supplier
      - NEXT_TEST=TEST2
      - NEXT_PUBLIC_URL_API=http://localhost:3600/api/v1
      - NEXT_PUBLIC_SOCKET_SERVER_URL=http://localhost:3600
    command: sh -c "yarn dev"
